kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-term-tools
  labels:
    app: web-term-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-term-tools
  template:
    metadata:
      labels:
        app: web-term-tools
    spec:
      containers:
        - name: web-term-tools
          image: ghcr.io/dimitrim/web-term-tools:main
---
apiVersion: v1
kind: Service
metadata:
  name: web-term-tools
spec:
  type: NodePort
  ports:
    - port: 7681
      targetPort: 7681
      nodePort: 31111
      protocol: TCP
  selector:
    app: web-term-tools
